"""
Generate the seamless paper texture the page is laid on.

Drawn rather than generated by an image model, for one reason: this has to
tile. A generated photograph of paper shows its seams the moment it repeats
across a 1860px page, and "make it seamless" is not something you can ask for
and verify by eye. Noise built in the frequency domain is periodic by
construction, so the tile meets itself exactly on all four edges.

The output is deliberately *not* a colour. It is a transparency map — dark
brown where the paper is grubby, pale where a fibre catches the light — so the
page colour underneath stays a CSS variable that can be changed without
regenerating anything.

What is in it: two octaves of fractal mottling, a fine fibre grain, a handful
of scratches, and a couple of long soft creases. All of them wrap.

Usage:  python tools/make_paper.py
"""

import numpy as np
from PIL import Image, ImageFilter
from pathlib import Path

OUT = (Path(__file__).resolve().parent.parent
       / "korea_service_record" / "static" / "images" / "paper.png")

SIZE = 512
SEED = 20260910

# One knob for the whole texture. The first attempt ran at 1.0 and read as
# damage on the screen rather than age in the paper — the long scratches in
# particular caught the eye across an otherwise quiet page. Background texture
# only works when you have to look for it.
STRENGTH = 0.38
SCRATCHES = 4
CREASES = 1

# Per-pixel gaussian grain, on top of the fractal octaves. Independent noise
# needs no periodicity treatment — neighbouring pixels are uncorrelated
# everywhere, so the tile boundary looks like any other boundary.
GRAIN = 0.22

DARK = (74, 52, 33)      # grime, in the palette's shadow brown
LIGHT = (255, 250, 238)  # a fibre catching the light


def periodic_noise(size: int, beta: float, rng: np.random.Generator) -> np.ndarray:
    """
    Fractal noise that tiles exactly.

    Built as a spectrum with 1/f**beta amplitude and random phase, then
    inverse-transformed. Because every component is a whole number of cycles
    across the tile, the result is periodic — no blending or mirroring needed,
    and no seam to hunt for afterwards.
    """
    fx = np.fft.fftfreq(size)[:, None]
    fy = np.fft.fftfreq(size)[None, :]
    radius = np.sqrt(fx ** 2 + fy ** 2)
    radius[0, 0] = 1.0
    amplitude = radius ** (-beta)
    amplitude[0, 0] = 0.0                      # no DC: the mean is the CSS colour
    spectrum = amplitude * np.exp(2j * np.pi * rng.random((size, size)))
    field = np.fft.ifft2(spectrum).real
    field -= field.mean()
    peak = np.abs(field).max()
    return field / peak if peak else field


def draw_streak(canvas: np.ndarray, rng: np.random.Generator,
                length_range, strength: float, wobble: float) -> None:
    """One scratch or crease, wrapped at the tile edges."""
    size = canvas.shape[0]
    x, y = rng.uniform(0, size, 2)
    angle = rng.uniform(0, np.pi)
    length = rng.uniform(*length_range) * size
    steps = int(length * 2)
    t = np.linspace(0, length, steps)

    # A drifting perpendicular offset: a dead straight line reads as a rule,
    # not as damage.
    drift = np.cumsum(rng.normal(0, wobble, steps))
    xs = (x + np.cos(angle) * t + np.sin(angle) * drift) % size
    ys = (y + np.sin(angle) * t - np.cos(angle) * drift) % size

    # Fade both ends so a scratch does not begin and end abruptly.
    taper = np.minimum(1.0, np.minimum(t, length - t) / (length * 0.25))
    np.add.at(canvas, (ys.astype(int), xs.astype(int)), strength * taper)


def main() -> int:
    rng = np.random.default_rng(SEED)

    mottle = (0.62 * periodic_noise(SIZE, 2.6, rng)
              + 0.38 * periodic_noise(SIZE, 1.5, rng))
    grain = periodic_noise(SIZE, 0.6, rng)
    # Clipped at three sigma: a handful of extreme pixels would read as dust
    # specks rather than as grain.
    speckle = np.clip(rng.normal(0.0, 1.0, (SIZE, SIZE)), -3, 3) / 3.0
    field = (1.0 - GRAIN) * (0.78 * mottle + 0.22 * grain) + GRAIN * speckle

    scratches = np.zeros((SIZE, SIZE), dtype=np.float64)
    for _ in range(SCRATCHES):
        draw_streak(scratches, rng, (0.25, 0.8), 1.0, 0.35)
    for _ in range(CREASES):                   # longer, softer creases
        draw_streak(scratches, rng, (0.9, 1.4), 0.75, 0.12)
    scratches = np.asarray(
        Image.fromarray((np.clip(scratches, 0, 3) * 85).astype(np.uint8))
             .filter(ImageFilter.GaussianBlur(0.7)), dtype=np.float64) / 255.0

    # Dark side and light side kept apart: grime is browner and stronger than
    # the highlights, which are barely there.
    dark = (np.clip(-field, 0, 1) * 0.30 + scratches * 0.20) * STRENGTH
    light = np.clip(field, 0, 1) * 0.13 * STRENGTH

    rgba = np.zeros((SIZE, SIZE, 4), dtype=np.float64)
    total = dark + light
    with np.errstate(invalid="ignore", divide="ignore"):
        mix = np.where(total > 0, dark / np.maximum(total, 1e-9), 0.0)
    for c in range(3):
        rgba[:, :, c] = DARK[c] * mix + LIGHT[c] * (1.0 - mix)
    rgba[:, :, 3] = np.clip(total, 0, 1) * 255.0

    img = Image.fromarray(rgba.astype(np.uint8), "RGBA")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT, optimize=True)

    alpha = rgba[:, :, 3]
    print(f"  {OUT.name}: {SIZE}x{SIZE}  {OUT.stat().st_size // 1024} KB")
    print(f"  alpha: mean {alpha.mean():.1f}  max {alpha.max():.0f}  "
          f"(0 = invisible, 255 = opaque)")
    # A tile that does not wrap shows up as a hard edge here.
    seam_x = np.abs(alpha[:, 0] - alpha[:, -1]).mean()
    seam_y = np.abs(alpha[0, :] - alpha[-1, :]).mean()
    interior = np.abs(np.diff(alpha, axis=1)).mean()
    print(f"  seam check: edge step {seam_x:.1f}/{seam_y:.1f} vs "
          f"interior {interior:.1f} — seamless if comparable")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
